import type { PerspectiveCamera } from 'three'; import { Vector3 } from 'three'; import type { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js'; import type { ShelfLayout,ShelfSlot } from '@/types/api'; import { cameraFocus,MIN_PARCEL_CAMERA_DISTANCE,parcelCameraView,slotWorldPosition,type Vec3 } from './sceneMath'; import { sceneBounds } from './sceneBounds'

export function interpolateCameraOffset(from:Vector3,to:Vector3,t:number,minimumRadius=MIN_PARCEL_CAMERA_DISTANCE){
  const fromRadius=Math.max(minimumRadius,from.length()),toRadius=Math.max(minimumRadius,to.length())
  const fromAzimuth=Math.atan2(from.x,from.z),toAzimuth=Math.atan2(to.x,to.z)
  let delta=toAzimuth-fromAzimuth
  if(delta>Math.PI)delta-=Math.PI*2
  if(delta<-Math.PI)delta+=Math.PI*2
  const fromElevation=Math.asin(Math.max(-1,Math.min(1,from.y/fromRadius)))
  const toElevation=Math.asin(Math.max(-1,Math.min(1,to.y/toRadius)))
  const radius=fromRadius+(toRadius-fromRadius)*t,azimuth=fromAzimuth+delta*t,elevation=fromElevation+(toElevation-fromElevation)*t
  const horizontal=radius*Math.cos(elevation)
  return new Vector3(Math.sin(azimuth)*horizontal,Math.sin(elevation)*radius,Math.cos(azimuth)*horizontal)
}

export class CameraController { private animation=0; constructor(private camera:PerspectiveCamera,private controls:OrbitControls,private layouts:()=>ShelfLayout[],private slots:()=>ShelfSlot[]){} focusSlot(id:number){const s=this.slots().find(x=>x.id===id),l=s&&this.layouts().find(x=>x.shelfId===s.shelfId);if(s&&l)this.animate(cameraFocus(l,slotWorldPosition(l,s)))} focusShelf(id:number){const l=this.layouts().find(x=>x.shelfId===id);if(l)this.animate(cameraFocus(l,{x:l.positionX,y:l.height/2,z:l.positionZ}))} focusParcelWorld(target:Vec3,layout:ShelfLayout){this.animate(parcelCameraView(layout,target,this.layouts()))} resetCamera(){const b=sceneBounds(this.layouts()),d=Math.max(b.spanX,b.spanZ)*.85;this.animate({position:{x:b.centerX+d*.7,y:b.maxHeight+d*.55,z:b.centerZ+d},target:{x:b.centerX,y:b.maxHeight*.4,z:b.centerZ}})} topView(){const b=sceneBounds(this.layouts()),d=Math.max(b.spanX,b.spanZ);this.animate({position:{x:b.centerX,y:b.maxHeight+d,z:b.centerZ+.01},target:{x:b.centerX,y:0,z:b.centerZ}})} frontView(){const b=sceneBounds(this.layouts()),d=Math.max(b.spanX,b.spanZ);this.animate({position:{x:b.centerX,y:b.maxHeight*.8,z:b.centerZ+d},target:{x:b.centerX,y:b.maxHeight*.4,z:b.centerZ}})} cancelAnimation(){cancelAnimationFrame(this.animation)} private animate(view:{position:{x:number;y:number;z:number};target:{x:number;y:number;z:number}}){this.cancelAnimation();const targetFrom=this.controls.target.clone(),start=performance.now(),target=new Vector3(view.target.x,view.target.y,view.target.z),fromOffset=this.camera.position.clone().sub(targetFrom),toOffset=new Vector3(view.position.x,view.position.y,view.position.z).sub(target);const tick=(now:number)=>{const t=Math.min(1,(now-start)/800),e=1-Math.pow(1-t,3),currentTarget=new Vector3().lerpVectors(targetFrom,target,e),offset=interpolateCameraOffset(fromOffset,toOffset,e);this.controls.target.copy(currentTarget);this.camera.position.copy(currentTarget).add(offset);this.camera.up.set(0,1,0);this.controls.update();if(t<1)this.animation=requestAnimationFrame(tick)};this.animation=requestAnimationFrame(tick)} }
