import{describe,expect,it}from'vitest';import{Mesh,Object3D,Vector3}from'three';import{SceneIndex}from'./SceneIndex';import{resolveParcelFocus}from'./parcelFocus';import{MIN_PARCEL_CAMERA_DISTANCE,parcelCameraView,shelfFront,slotWorldPosition}from'./sceneMath';import{interpolateCameraOffset}from'./CameraController';import type{ShelfLayout,WarehouseSnapshot}from'@/types/api'
const layout=(shelfId:number,x:number,z:number,rotationY:number):ShelfLayout=>({shelfId,positionX:x,positionY:0,positionZ:z,rotationY,width:3.6,height:2.6,depth:.8,columns:6,levels:5})
const layouts=[layout(1,-6,-3,0),layout(2,-2,-3,0),layout(5,-6,2,Math.PI),layout(6,-2,2,Math.PI),layout(9,3,6,Math.PI/2)]
const slots=layouts.flatMap((l,i)=>[0,5].map((columnIndex,j)=>({id:100+i*2+j,shelfId:l.shelfId,slotCode:`S-${i}-${j}`,levelIndex:1,columnIndex,enabled:true})))
const parcels=slots.map((slot,i)=>({id:1000+i,trackingNo:`T-${i}`,courierCompany:'顺丰',customerId:1,shelfId:slot.shelfId,slotId:slot.id,status:'IN_STOCK',arrivedAt:'2026-01-01',pickedUpAt:null,operatorId:1,remark:'',version:0}))
const data={shelves:layouts.map(l=>({id:l.shelfId,shelfCode:`S-${l.shelfId}`,zone:'Z',capacity:30,occupied:2,status:'ACTIVE' as const})),layouts,slots,parcels} satisfies WarehouseSnapshot
function indexed(){const index=new SceneIndex();parcels.forEach((p,i)=>{const point=slotWorldPosition(layouts.find(l=>l.shelfId===p.shelfId)!,slots[i]!);const parent=new Object3D(),mesh=new Mesh();parent.position.set(point.x,point.y,point.z);parent.add(mesh);parent.userData.parcelId=p.id;index.parcels.set(p.id,parent)});return index}
describe('parcel camera focus',()=>{
  it('uses distinct actual mesh targets for first/last columns and shelves',()=>{const index=indexed(),first=resolveParcelFocus(1000,data,index)!,last=resolveParcelFocus(1001,data,index)!,other=resolveParcelFocus(1002,data,index)!;expect(first.target.x).not.toBe(last.target.x);expect(first.target.x).not.toBe(other.target.x);expect(first.target.distanceTo(index.parcels.get(1000)!.getWorldPosition(new Vector3()))).toBeLessThan(1e-8);expect([first.parcel.trackingNo,first.layout.shelfId,first.slot.slotCode]).toEqual(['T-0',1,'S-0-0'])})
  it('keeps every rotation in its logical front hemisphere',()=>{for(const rotation of[0,Math.PI,Math.PI/2,-Math.PI/2]){const current=layout(50+rotation,0,0,rotation),target={x:0,y:1,z:0},view=parcelCameraView(current,target,[current]),front=shelfFront(current),offset={x:view.position.x-target.x,z:view.position.z-target.z};expect(offset.x*front.x+offset.z*front.z).toBeGreaterThan(0)}})
  it('separates front and rear rows without choosing a back view',()=>{const index=indexed(),front=resolveParcelFocus(1000,data,index)!,rear=resolveParcelFocus(1004,data,index)!,side=resolveParcelFocus(1008,data,index)!;const frontView=parcelCameraView(front.layout,front.target,layouts),rearView=parcelCameraView(rear.layout,rear.target,layouts),sideView=parcelCameraView(side.layout,side.target,layouts);expect(front.target.z).toBeCloseTo(-3);expect(rear.target.z).toBeCloseTo(2);expect(frontView.position.z).toBeGreaterThan(front.target.z);expect(rearView.position.z).toBeLessThan(rear.target.z);expect(sideView.position.x).toBeGreaterThan(side.target.x)})
  it('shortens or offsets around an opposite shelf but never jumps behind',()=>{const selected=layout(70,0,0,0),blocker=layout(71,0,2,Math.PI),target={x:0,y:1,z:0},unblocked=parcelCameraView(selected,target,[selected]),blocked=parcelCameraView(selected,target,[selected,blocker]),front=shelfFront(selected);expect(new Vector3(blocked.position.x-target.x,blocked.position.y-target.y,blocked.position.z-target.z).dot(new Vector3(front.x,0,front.z))).toBeGreaterThan(0);expect(new Vector3(blocked.position.x-target.x,0,blocked.position.z-target.z).length()).toBeLessThanOrEqual(new Vector3(unblocked.position.x-target.x,0,unblocked.position.z-target.z).length())})
  it('uses a shortest-arc transition with a stable minimum radius',()=>{const from=new Vector3(0,.8,2),to=new Vector3(0,.8,-2);for(let step=0;step<=20;step++){const offset=interpolateCameraOffset(from,to,step/20);expect(offset.length()).toBeGreaterThanOrEqual(MIN_PARCEL_CAMERA_DISTANCE-.0001);expect(Number.isFinite(offset.x+offset.y+offset.z)).toBe(true)}})
  it('does not confuse parcel ids with slot ids',()=>{expect(resolveParcelFocus(slots[0]!.id,data,indexed())).toBeNull()})
})
