import { createPinia, setActivePinia } from 'pinia'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { useWarehouseStore } from './warehouse'
const snapshot = { shelves:[{id:1,shelfCode:'A-01',zone:'A',capacity:2,occupied:0,status:'ACTIVE'}], layouts:[], slots:[{id:10,shelfId:1,slotCode:'A-01-01-01',levelIndex:0,columnIndex:0,enabled:true},{id:11,shelfId:1,slotCode:'A-01-01-02',levelIndex:0,columnIndex:1,enabled:true}], parcels:[{id:5,trackingNo:'TRACK-5',courierCompany:'SF',customerId:1,shelfId:null,slotId:null,status:'IN_STOCK',arrivedAt:'2026-01-01T10:00',pickedUpAt:null,operatorId:1,remark:'',version:0}] } as const
function response(data: unknown, status=200) { return new Response(JSON.stringify({success:status<400,data:status<400?data:null,message:status<400?null:'冲突',code:status===409?'SLOT_OCCUPIED':null}),{status}) }
describe('warehouse store relocation',()=>{beforeEach(()=>{setActivePinia(createPinia());vi.unstubAllGlobals()})
it('loads snapshot and commits server result',async()=>{const fetchMock=vi.fn().mockResolvedValueOnce(response(snapshot)).mockResolvedValueOnce(response({parcel:{...snapshot.parcels[0],slotId:10,shelfId:1,version:1},relocation:{}}));vi.stubGlobal('fetch',fetchMock);const store=useWarehouseStore();await store.refresh();expect(store.waitingParcels).toHaveLength(1);await expect(store.relocate(5,10)).resolves.toBe(true);expect(store.selectedParcel?.version ?? store.snapshot?.parcels[0]?.version).toBe(1);expect(store.snapshot?.parcels[0]?.slotId).toBe(10)})
it('rolls back preview and refreshes after 409',async()=>{const fetchMock=vi.fn().mockResolvedValueOnce(response(snapshot)).mockResolvedValueOnce(response(null,409)).mockResolvedValueOnce(response(snapshot));vi.stubGlobal('fetch',fetchMock);const store=useWarehouseStore();await store.refresh();await expect(store.relocate(5,10)).resolves.toBe(false);expect(store.snapshot?.parcels[0]?.slotId).toBeNull();expect(store.error).toContain('已刷新')})
it('rejects occupied targets locally',async()=>{vi.stubGlobal('fetch',vi.fn().mockResolvedValue(response({...snapshot,parcels:[...snapshot.parcels,{...snapshot.parcels[0],id:6,trackingNo:'TRACK-6',slotId:10}]})));const store=useWarehouseStore();await store.refresh();expect(store.isSlotAvailable(store.snapshot!.slots[0]!,5)).toBe(false);await expect(store.relocate(5,10)).resolves.toBe(false)})})
