package com.parcelstationx.ai;

public enum AiIntent {
  PARCEL_SEARCH,
  OVERDUE_PARCELS,
  PARCEL_LOCATE,
  SHELF_AVAILABILITY,
  SHELF_UTILIZATION,
  UNRESOLVED_EXCEPTIONS,
  TODAY_SUMMARY,
  UNSUPPORTED
}
