export type ChartKind='bar'|'line'|'pie'|'donut'
export interface ChartSeriesInput{name:string;values:number[];color?:string;yAxisIndex?:number}
export interface ChartOptionInput{type:ChartKind;title:string;labels:string[];values?:number[];color?:string;series?:ChartSeriesInput[]}
const palette=['#29c7e8','#77e6a1','#7aa7ff','#ff9b5e','#b58aff','#ff6577']
export function buildChartOption(input:ChartOptionInput){
  if(input.type==='pie'||input.type==='donut')return{backgroundColor:'transparent',tooltip:{trigger:'item',formatter:'{b}: {c} ({d}%)'},legend:{type:'scroll',bottom:0,textStyle:{color:'#8195a9'}},series:[{name:input.title,type:'pie',radius:input.type==='donut'?['42%','68%']:'66%',center:['50%','44%'],data:input.labels.map((name,index)=>({name,value:input.values?.[index]??0})),label:{color:'#b8cddd',formatter:'{b}\n{d}%'},itemStyle:{borderColor:'#091927',borderWidth:2},color:palette}]}
  const sources=input.series?.length?input.series:[{name:input.title,values:input.values??[],color:input.color}]
  return{backgroundColor:'transparent',grid:{left:48,right:input.type==='line'?48:18,top:input.type==='line'?58:38,bottom:34},tooltip:{trigger:'axis'},legend:{show:input.type==='line',top:8,textStyle:{color:'#9bb1c1'}},xAxis:{type:'category',data:input.labels,axisLabel:{color:'#8195a9'},axisLine:{lineStyle:{color:'#26394b'}}},yAxis:input.type==='line'?[{type:'value',axisLabel:{color:'#8195a9'},splitLine:{lineStyle:{color:'#162838'}}},{type:'value',axisLabel:{color:'#7aa7ff'},splitLine:{show:false}}]:{type:'value',axisLabel:{color:'#8195a9'},splitLine:{lineStyle:{color:'#162838'}}},series:sources.map((source,index)=>input.type==='line'?{name:source.name,type:'line',data:source.values,smooth:true,showSymbol:false,yAxisIndex:source.yAxisIndex??0,lineStyle:{width:2,color:source.color??palette[index]},itemStyle:{color:source.color??palette[index]},areaStyle:{opacity:.06}}:{name:source.name,type:'bar',data:source.values,itemStyle:{color:source.color??palette[index],borderRadius:[4,4,0,0]}})}
}
