<script setup lang="ts">
import { nextTick,onBeforeUnmount,onMounted,ref,watch } from 'vue';import { useWarehouseStore } from '@/stores/warehouse';import { WarehouseScene } from '@/three/WarehouseScene'
const store=useWarehouseStore(),canvas=ref<HTMLElement>(),search=ref('');let scene:WarehouseScene|undefined
async function mount(){if(!store.snapshot)await store.refresh();await nextTick();if(canvas.value&&store.snapshot){scene?.dispose();scene=new WarehouseScene(canvas.value,store.snapshot,id=>{store.selectParcel(id);focus(id)})}}
function focus(id:number){const p=store.snapshot?.parcels.find(x=>x.id===id);if(p?.slotId)scene?.camera.focusParcel(p.slotId)}
function find(){const p=store.snapshot?.parcels.find(x=>x.trackingNo.toLowerCase().includes(search.value.toLowerCase()));if(p){store.selectParcel(p.id);focus(p.id)}}
onMounted(mount);watch(()=>store.lastSyncAt,mount);onBeforeUnmount(()=>scene?.dispose())
</script>
<template><section class="page twin-page"><header class="page-heading"><div><p class="eyebrow">LIVE SPATIAL MODEL</p><h1>仓库数字孪生</h1></div><div class="twin-tools"><input v-model="search" placeholder="输入运单号定位" @keyup.enter="find"><button class="ghost" @click="find">定位</button><button class="ghost" @click="scene?.camera.frontView()">正视</button><button class="ghost" @click="scene?.camera.topView()">顶视</button><button class="ghost" @click="scene?.camera.resetCamera()">全景</button></div></header><div class="twin-layout"><div ref="canvas" class="twin-canvas"></div><aside class="detail-panel"><template v-if="store.selectedParcel"><p class="eyebrow">SELECTED</p><h2>{{store.selectedParcel.trackingNo}}</h2><dl><dt>状态</dt><dd>{{store.selectedParcel.status}}</dd><dt>仓位</dt><dd>{{store.snapshot?.slots.find(s=>s.id===store.selectedParcel?.slotId)?.slotCode}}</dd><dt>快递</dt><dd>{{store.selectedParcel.courierCompany}}</dd></dl><button class="primary" @click="focus(store.selectedParcel.id)">镜头定位</button></template><div v-else class="empty">点击场景中的快件查看详情</div></aside></div></section></template>
