<script setup lang="ts">
import { computed,nextTick,onBeforeUnmount,onMounted,reactive,ref,watch } from 'vue'
import { useRoute } from 'vue-router'
import { apiRequest } from '@/api/client'
import { useWarehouseStore } from '@/stores/warehouse'
import { WarehouseScene } from '@/three/WarehouseScene'
import type { ParcelDetails } from '@/types/api'
import type { ParcelHover } from '@/three/HoverController'
import { dwellText,snapshotTooltip } from '@/features/parcelTooltip'
const store=useWarehouseStore(),canvas=ref<HTMLElement>(),search=ref(''),hover=ref<ParcelHover|null>(null),hoverDetail=ref<ParcelDetails|null>(null),selectedDetail=ref<ParcelDetails|null>(null),outboundCode=ref(''),confirmOutbound=ref(false),busy=ref(false),actionError=ref(''),actionNotice=ref('')
const inbound=reactive({trackingNo:'',courierCompany:'顺丰',customerMobile:'13900000001',remark:'3D 快速入库'})
const route=useRoute();let scene:WarehouseScene|undefined;const hoverDetails=new Map<number,ParcelDetails>(),hoverRequests=new Map<number,Promise<ParcelDetails>>()
async function mount(){if(!store.snapshot)await store.refresh();await nextTick();if(canvas.value&&store.snapshot){scene?.dispose();scene=new WarehouseScene(canvas.value,store.snapshot,select,relocate3d,showHover);const id=Number(route.query.parcelId);if(id){void select(id);focus(id)}}}
function focus(id:number){scene?.focusParcel(id)}
function find(){const p=store.snapshot?.parcels.find(x=>x.trackingNo.toLowerCase().includes(search.value.toLowerCase()));if(p){void select(p.id);focus(p.id)}}
async function detail(id:number){return apiRequest<ParcelDetails>(`/api/parcels/${id}/details`)}
async function select(id:number){store.selectParcel(id);selectedDetail.value=await detail(id);outboundCode.value='';confirmOutbound.value=false}
function showHover(value:ParcelHover|null){hover.value=value;if(!value){hoverDetail.value=null;return}hoverDetail.value=hoverDetails.get(value.parcelId)??null;if(hoverDetail.value||hoverRequests.has(value.parcelId))return;const request=detail(value.parcelId);hoverRequests.set(value.parcelId,request);void request.then(result=>{hoverRequests.delete(value.parcelId);hoverDetails.set(value.parcelId,result);if(hover.value?.parcelId===value.parcelId)hoverDetail.value=result}).catch(()=>hoverRequests.delete(value.parcelId))}
async function refreshAfterMutation(){await store.refresh();if(store.selectedParcelId)selectedDetail.value=await detail(store.selectedParcelId)}
async function relocate3d(parcelId:number,slotId:number){const ok=await store.relocate(parcelId,slotId,'3d drag and snap');if(ok)await refreshAfterMutation();return ok}
async function createInbound(){busy.value=true;actionError.value='';actionNotice.value='';try{const parcel=await apiRequest<{id:number}>('/api/parcels/inbound',{method:'POST',body:JSON.stringify(inbound)});inbound.trackingNo='';actionNotice.value='快件已进入 3D 入库暂存区';await refreshAfterMutation();await select(parcel.id)}catch(e){actionError.value=e instanceof Error?e.message:'入库失败'}finally{busy.value=false}}
async function outbound(){if(!selectedDetail.value)return;if(!confirmOutbound.value){confirmOutbound.value=true;return}busy.value=true;actionError.value='';try{await apiRequest(`/api/parcels/${selectedDetail.value.parcel.id}/outbound`,{method:'POST',body:JSON.stringify({pickupCode:outboundCode.value})});actionNotice.value='快件已出库';confirmOutbound.value=false;await refreshAfterMutation()}catch(e){actionError.value=e instanceof Error?e.message:'出库失败'}finally{busy.value=false}}
const selected=computed(()=>selectedDetail.value),hoverSummary=computed(()=>hover.value&&store.snapshot?snapshotTooltip(store.snapshot,hover.value.parcelId):null)
onMounted(mount);watch(()=>store.lastSyncAt,mount);onBeforeUnmount(()=>scene?.dispose())
</script>
<template><section class="page twin-page"><header class="page-heading"><div><p class="eyebrow">LIVE SPATIAL MODEL</p><h1>仓库数字孪生</h1></div><div class="twin-tools"><input v-model="search" placeholder="输入运单号定位" @keyup.enter="find"><button class="ghost" @click="find">定位</button><button class="ghost" @click="scene?.camera.frontView()">正视</button><button class="ghost" @click="scene?.camera.topView()">顶视</button><button class="ghost" @click="scene?.camera.resetCamera()">全景</button></div></header><form class="twin-inbound" @submit.prevent="createInbound"><input v-model="inbound.trackingNo" required placeholder="新运单号" aria-label="3D 新运单号"><input v-model="inbound.customerMobile" required placeholder="客户手机号" aria-label="3D 客户手机号"><select v-model="inbound.courierCompany"><option>顺丰</option><option>中通</option><option>圆通</option><option>韵达</option></select><button class="primary compact" :disabled="busy">快速入库到暂存区</button><span class="success">{{actionNotice}}</span><span class="error">{{actionError}}</span></form><div class="twin-layout"><div ref="canvas" class="twin-canvas"><div v-if="hover&&hoverSummary" class="parcel-tooltip" :style="{left:`${hover.x}px`,top:`${hover.y}px`}"><b>{{hoverSummary.trackingNo}}</b><span>{{hoverSummary.courierCompany}} · {{hoverSummary.status}}</span><span>{{hoverSummary.slotCode}}</span><span v-if="hoverDetail?.customer">{{hoverDetail.customer.name}} · {{hoverDetail.customer.maskedMobile}}</span><span>到站 {{hoverSummary.arrivedAt.replace('T',' ')}}</span><span>停留 {{dwellText(hoverSummary.arrivedAt)}}</span></div></div><aside class="detail-panel"><template v-if="selected"><p class="eyebrow">SELECTED</p><h2>{{selected.parcel.trackingNo}}</h2><dl><dt>状态</dt><dd>{{selected.parcel.status}}</dd><dt>仓位</dt><dd>{{selected.slotCode??'入库暂存区'}}</dd><dt>快递</dt><dd>{{selected.parcel.courierCompany}}</dd><dt>客户</dt><dd>{{selected.customer?.name}} · {{selected.customer?.maskedMobile}}</dd><dt>取件码</dt><dd>{{selected.pickupCode}}</dd><dt>到站</dt><dd>{{selected.parcel.arrivedAt.replace('T',' ')}}</dd><dt>停留</dt><dd>{{dwellText(selected.parcel.arrivedAt)}}</dd></dl><button v-if="selected.parcel.slotId" class="primary" @click="focus(selected.parcel.id)">镜头定位</button><form v-if="selected.parcel.status==='IN_STOCK'" class="outbound-form" @submit.prevent="outbound"><input v-model="outboundCode" required placeholder="输入取件码" aria-label="3D 出库取件码"><p v-if="confirmOutbound" class="error">请再次确认：出库后该快件将离开当前仓位。</p><button class="primary" :disabled="busy">{{confirmOutbound?'再次确认出库':'确认出库'}}</button></form></template><div v-else class="empty">悬停查看摘要，点击或拖拽快件执行作业</div></aside></div></section></template>
