<script setup lang="ts">
import{computed,onMounted,reactive,ref}from'vue';import{apiRequest}from'@/api/client';import{useWarehouseStore}from'@/stores/warehouse';import{applyExceptionAdviceDraft}from'@/features/aiAdvice';import type{AiExceptionAdvice,ExceptionRecord}from'@/types/api'
const warehouse=useWarehouseStore(),items=ref<ExceptionRecord[]>([]),selected=ref<ExceptionRecord|null>(null),loading=ref(false),error=ref(''),notice=ref(''),filters=reactive({query:'',status:'',type:''}),create=reactive({parcelId:0,type:'DAMAGED',description:''}),resolve=reactive({targetStatus:'IN_STOCK',resolution:''})
const advice=ref<AiExceptionAdvice|null>(null),adviceLoading=ref(false),adviceError=ref('')
const filtered=computed(()=>items.value.filter(x=>(!filters.query||[String(x.parcelId),x.description,tracking(x.parcelId)].some(v=>v.toLowerCase().includes(filters.query.toLowerCase())))&&(!filters.status||x.status===filters.status)&&(!filters.type||x.exceptionType===filters.type)))
const parcels=computed(()=>warehouse.snapshot?.parcels.filter(p=>p.status==='IN_STOCK')??[]);const tracking=(id:number)=>warehouse.snapshot?.parcels.find(p=>p.id===id)?.trackingNo??`#${id}`;const fmt=(v:string|null)=>v?new Date(v).toLocaleString():'—'
async function load(){loading.value=true;error.value='';try{[items.value]=await Promise.all([apiRequest<ExceptionRecord[]>('/api/exceptions'),warehouse.refresh()]);selected.value=selected.value?items.value.find(x=>x.id===selected.value?.id)??null:null}catch(e){error.value=e instanceof Error?e.message:'异常数据加载失败'}finally{loading.value=false}}
async function createOne(){error.value='';try{await apiRequest(`/api/parcels/${create.parcelId}/exception`,{method:'POST',body:JSON.stringify({exceptionType:create.type,description:create.description})});notice.value='异常已登记';create.description='';await load()}catch(e){error.value=e instanceof Error?e.message:'登记失败'}}
async function resolveOne(){if(!selected.value)return;error.value='';try{await apiRequest(`/api/exceptions/${selected.value.id}/resolve`,{method:'POST',body:JSON.stringify(resolve)});notice.value='异常已处理';resolve.resolution='';await load()}catch(e){error.value=e instanceof Error?e.message:'处理失败'}}
async function getAdvice(){if(!selected.value)return;adviceLoading.value=true;adviceError.value='';advice.value=null;try{advice.value=await apiRequest<AiExceptionAdvice>('/api/ai/exception-advice',{method:'POST',body:JSON.stringify({exceptionId:selected.value.id})})}catch(e){adviceError.value=e instanceof Error?e.message:'AI 暂时不可用'}finally{adviceLoading.value=false}}
function useAdvice(){if(advice.value)applyExceptionAdviceDraft(advice.value,resolve)}
onMounted(load)
</script>
<template><section class="page"><header class="page-heading"><div><p class="eyebrow">EXCEPTION OPERATIONS</p><h1>异常中心</h1><p>登记和处理均由服务端事务同步快件、事件与日志</p></div><button class="ghost" @click="load">刷新</button></header><div class="filter-grid"><input v-model="filters.query" placeholder="运单号 / 描述"><select v-model="filters.status"><option value="">全部状态</option><option>OPEN</option><option>RESOLVED</option></select><select v-model="filters.type"><option value="">全部类型</option><option>DAMAGED</option><option>LOST</option><option>OVERDUE</option><option>OTHER</option></select></div><p v-if="error" class="error" role="alert">{{error}}</p><p v-if="notice" class="success">{{notice}}</p>
<div class="management-layout"><div><form class="action-card" @submit.prevent="createOne"><h3>登记异常</h3><select v-model.number="create.parcelId" required><option :value="0" disabled>选择在库快件</option><option v-for="p in parcels" :key="p.id" :value="p.id">{{p.trackingNo}}</option></select><select v-model="create.type"><option>DAMAGED</option><option>WRONG_SORT</option><option>REFUSED</option><option>LOST_SUSPECTED</option><option>OVERDUE</option><option>OTHER</option></select><input v-model="create.description" required placeholder="异常描述"><button class="primary compact">登记</button></form><div v-if="loading" class="state-panel">正在加载异常…</div><div v-else-if="!filtered.length" class="state-panel">暂无异常记录</div><div v-else class="data-table-wrap"><table><thead><tr><th>快件</th><th>类型</th><th>描述</th><th>状态</th><th>创建时间</th></tr></thead><tbody><tr v-for="x in filtered" :key="x.id" :class="{selected:selected?.id===x.id}" @click="selected=x"><td>{{tracking(x.parcelId)}}</td><td>{{x.exceptionType}}</td><td>{{x.description}}</td><td><span class="status-pill">{{x.status}}</span></td><td>{{fmt(x.createdAt)}}</td></tr></tbody></table></div></div>
<aside class="detail-panel"><template v-if="selected"><p class="eyebrow">EXCEPTION DETAIL</p><h2>{{tracking(selected.parcelId)}}</h2><dl><dt>类型</dt><dd>{{selected.exceptionType}}</dd><dt>描述</dt><dd>{{selected.description}}</dd><dt>状态</dt><dd>{{selected.status}}</dd><dt>创建</dt><dd>{{fmt(selected.createdAt)}} · #{{selected.createdBy}}</dd><dt>处理</dt><dd>{{fmt(selected.handledAt)}} · {{selected.handledBy?'#'+selected.handledBy:'—'}}</dd><dt>结果</dt><dd>{{selected.resolution??'—'}}</dd></dl><section v-if="selected.status==='OPEN'" class="action-card"><h3>AI 处置建议</h3><button class="ghost" :disabled="adviceLoading" @click="getAdvice">{{adviceLoading?'分析中…':'生成建议'}}</button><p v-if="adviceError" class="error">{{adviceError}}</p><div v-if="advice"><p><b>{{advice.suggestedType}} · {{advice.riskLevel}}</b></p><p>{{advice.reason}}</p><ol><li v-for="step in advice.steps" :key="step">{{step}}</li></ol><button class="ghost" @click="useAdvice">采用建议（仅填草稿）</button></div></section><form v-if="selected.status==='OPEN'" @submit.prevent="resolveOne"><select v-model="resolve.targetStatus"><option value="IN_STOCK">恢复库存</option><option value="RETURNED">退回</option></select><textarea v-model="resolve.resolution" required placeholder="处理结果"></textarea><button class="primary">人工确认并完成处理</button></form></template><div v-else class="empty">选择异常查看详情</div></aside></div></section></template>
