<script setup lang="ts">
import {computed,onMounted,reactive,ref} from 'vue';import {useRouter} from 'vue-router';import {apiRequest} from '@/api/client';import {parcelFocusLocation}from'@/features/management';import {useWarehouseStore} from '@/stores/warehouse';import type{ParcelDetails}from '@/types/api'
const store=useWarehouseStore(),router=useRouter(),items=ref<ParcelDetails[]>([]),selected=ref<ParcelDetails|null>(null),loading=ref(false),error=ref('')
const filters=reactive({query:'',status:'',courier:'',shelf:'',slot:''})
const values=(key:'status'|'courierCompany'|'shelfCode'|'slotCode')=>[...new Set(items.value.map(x=>key==='status'?x.parcel.status:key==='courierCompany'?x.parcel.courierCompany:x[key]).filter(Boolean))]
const filtered=computed(()=>{const q=filters.query.toLowerCase();return items.value.filter(x=>(!q||[x.parcel.trackingNo,x.pickupCode,x.customer?.name,x.customer?.maskedMobile].some(v=>v?.toLowerCase().includes(q)))&&(!filters.status||x.parcel.status===filters.status)&&(!filters.courier||x.parcel.courierCompany===filters.courier)&&(!filters.shelf||x.shelfCode===filters.shelf)&&(!filters.slot||x.slotCode===filters.slot))})
const fmt=(v:string|null)=>v?new Date(v).toLocaleString():'—';const dwell=(v:string)=>Math.max(0,Math.floor((Date.now()-new Date(v).getTime())/86400000))+' 天'
async function load(){loading.value=true;error.value='';try{items.value=await apiRequest('/api/parcel-details');if(selected.value)selected.value=items.value.find(x=>x.parcel.id===selected.value?.parcel.id)??null}catch(e){error.value=e instanceof Error?e.message:'快件加载失败'}finally{loading.value=false}}
async function outbound(){if(!selected.value)return;try{await apiRequest(`/api/parcels/${selected.value.parcel.id}/outbound`,{method:'POST',body:JSON.stringify({pickupCode:selected.value.pickupCode})});await Promise.all([load(),store.refresh()])}catch(e){error.value=e instanceof Error?e.message:'出库失败'}}
function choose(x:ParcelDetails){selected.value=x;store.selectParcel(x.parcel.id)}
function locate(path:string){if(!selected.value)return;store.selectParcel(selected.value.parcel.id);router.push(parcelFocusLocation(selected.value.parcel.id,path==='/digital-twin'))}
onMounted(load)
</script>
<template><section class="page"><header class="page-heading"><div><p class="eyebrow">PARCEL CONTROL</p><h1>快件中心</h1><p>真实 API 查询、事件与换位历史</p></div><button class="ghost" @click="load">刷新</button></header>
<div class="filter-grid"><input v-model="filters.query" placeholder="运单号 / 取件码 / 收件人"><select v-model="filters.status"><option value="">全部状态</option><option v-for="v in values('status')" :key="v!">{{v}}</option></select><select v-model="filters.courier"><option value="">全部快递</option><option v-for="v in values('courierCompany')" :key="v!">{{v}}</option></select><select v-model="filters.shelf"><option value="">全部货架</option><option v-for="v in values('shelfCode')" :key="v!">{{v}}</option></select><select v-model="filters.slot"><option value="">全部仓位</option><option v-for="v in values('slotCode')" :key="v!">{{v}}</option></select></div>
<div v-if="loading" class="state-panel">正在加载快件…</div><div v-else-if="error" class="state-panel error" role="alert">{{error}}</div><div v-else-if="!filtered.length" class="state-panel">没有符合条件的快件</div>
<div v-else class="management-layout"><div class="data-table-wrap"><table><thead><tr><th>运单/快递</th><th>收件人</th><th>状态</th><th>货架/Slot</th><th>取件码</th><th>入库/停留</th></tr></thead><tbody><tr v-for="x in filtered" :key="x.parcel.id" :class="{selected:selected?.parcel.id===x.parcel.id}" @click="choose(x)"><td><b>{{x.parcel.trackingNo}}</b><small>{{x.parcel.courierCompany}}</small></td><td>{{x.customer?.name??'—'}}<small>{{x.customer?.maskedMobile}}</small></td><td><span class="status-pill">{{x.parcel.status}}</span></td><td>{{x.shelfCode??'待上架'}}<small>{{x.slotCode??'—'}}</small></td><td>{{x.pickupCode}}</td><td>{{fmt(x.parcel.arrivedAt)}}<small>{{dwell(x.parcel.arrivedAt)}}</small></td></tr></tbody></table></div>
<aside class="detail-panel"><template v-if="selected"><p class="eyebrow">PARCEL DETAIL</p><h2>{{selected.parcel.trackingNo}}</h2><dl><dt>快递</dt><dd>{{selected.parcel.courierCompany}}</dd><dt>客户</dt><dd>{{selected.customer?.name}} · {{selected.customer?.maskedMobile}}</dd><dt>状态</dt><dd>{{selected.parcel.status}}</dd><dt>位置</dt><dd>{{selected.shelfCode??'待上架'}} / {{selected.slotCode??'—'}}</dd><dt>取件码</dt><dd>{{selected.pickupCode}}</dd><dt>入库</dt><dd>{{fmt(selected.parcel.arrivedAt)}}</dd><dt>出库</dt><dd>{{fmt(selected.parcel.pickedUpAt)}}</dd><dt>停留</dt><dd>{{dwell(selected.parcel.arrivedAt)}}</dd><dt>操作员</dt><dd>{{selected.operator??'—'}}</dd></dl><div class="button-row"><button class="ghost" @click="locate('/warehouse')">在 2D 定位</button><button class="primary compact" @click="locate('/digital-twin')">在 3D 定位</button></div><button v-if="selected.parcel.status==='IN_STOCK'" class="primary" @click="outbound">确认出库</button><h3>事件时间线</h3><ol class="timeline"><li v-for="e in selected.events" :key="e.id"><b>{{e.eventType}}</b><small>{{fmt(e.createdAt)}} · {{e.description}}</small></li></ol><h3>换位历史</h3><ol class="timeline"><li v-for="r in selected.relocations" :key="r.id"><b>#{{r.fromSlotId??'待上架'}} → #{{r.newSlotId}}</b><small>{{fmt(r.createdAt)}} · {{r.reason}}</small></li></ol></template><div v-else class="empty">选择快件查看详情</div></aside></div></section></template>
