<script setup lang="ts">
import{computed,onMounted,reactive,ref}from'vue';import{apiRequest}from'@/api/client';import{useWarehouseStore}from'@/stores/warehouse';import type{Shelf,ShelfCreationResult,ShelfLayout,User,WarehouseAgentPlan,WarehouseSnapshot}from'@/types/api'
const warehouse=useWarehouseStore(),users=ref<User[]>([]),snapshot=ref<WarehouseSnapshot|null>(null),loading=ref(false),busy=ref(false),error=ref(''),notice=ref(''),preview=ref<ShelfCreationResult|null>(null),agentPlan=ref<WarehouseAgentPlan|null>(null),agentCommand=ref('帮我在现有货架后方的E区增加4个货架，每个5层6列，按现有货架网格与间距自动对齐'),selectedLayout=ref<ShelfLayout|null>(null)
const userForm=reactive({username:'',password:'',displayName:'',role:'STAFF'}),shelfForm=reactive({zone:'E区',count:4,levels:5,columns:6,width:3.6,height:2.6,depth:.8,layoutMode:'WIDE_MAIN_AISLE',maxShelvesPerRow:4,shelfGap:.6,aisleGap:2.5})
const info=computed(()=>({users:users.value.length,shelves:snapshot.value?.shelves.length??0,slots:snapshot.value?.slots.length??0})),selectedShelf=computed(()=>snapshot.value?.shelves.find(s=>s.id===selectedLayout.value?.shelfId))
async function load(){loading.value=true;error.value='';try{[users.value,snapshot.value]=await Promise.all([apiRequest<User[]>('/api/admin/users'),apiRequest<WarehouseSnapshot>('/api/admin/warehouse')]);await warehouse.refresh()}catch(e){error.value=e instanceof Error?e.message:'加载失败'}finally{loading.value=false}}
async function mutate(action:()=>Promise<unknown>,message:string){busy.value=true;error.value='';notice.value='';try{await action();notice.value=message;preview.value=null;await load()}catch(e){error.value=e instanceof Error?e.message:'更新失败'}finally{busy.value=false}}
async function addUser(){await mutate(()=>apiRequest('/api/admin/users',{method:'POST',body:JSON.stringify(userForm)}),'员工已新增');Object.assign(userForm,{username:'',password:'',displayName:'',role:'STAFF'})}
async function toggleUser(u:User){await mutate(()=>apiRequest(`/api/admin/users/${u.id}/enabled`,{method:'PUT',body:JSON.stringify({enabled:!u.enabled})}),'员工状态已更新')}
async function generatePreview(){busy.value=true;error.value='';try{preview.value=await apiRequest<ShelfCreationResult>('/api/admin/warehouse/auto-layout/preview',{method:'POST',body:JSON.stringify(shelfForm)})}catch(e){error.value=e instanceof Error?e.message:'预览失败'}finally{busy.value=false}}
async function confirmCreate(){await mutate(()=>apiRequest('/api/admin/warehouse/auto-layout/apply',{method:'POST',body:JSON.stringify(shelfForm)}),`已创建 ${preview.value?.shelfCount??shelfForm.count} 个货架，2D/3D 已刷新`)}
async function generateAgentPlan(){busy.value=true;error.value='';notice.value='';try{agentPlan.value=await apiRequest<WarehouseAgentPlan>('/api/ai/warehouse/plan',{method:'POST',body:JSON.stringify({command:agentCommand.value})})}catch(e){error.value=e instanceof Error?e.message:'AI 计划生成失败'}finally{busy.value=false}}
async function confirmAgentPlan(){if(!agentPlan.value)return;const count=agentPlan.value.preview.shelfCount;await mutate(()=>apiRequest(`/api/ai/warehouse/plans/${agentPlan.value!.id}/confirm`,{method:'POST'}),`AI 计划已确认：创建 ${count} 个货架，2D/3D 已刷新`);agentPlan.value=null}
async function cancelAgentPlan(){if(!agentPlan.value)return;await mutate(()=>apiRequest(`/api/ai/warehouse/plans/${agentPlan.value!.id}`,{method:'DELETE'}),'AI 计划已取消，未写入数据库');agentPlan.value=null}
function editLayout(x:ShelfLayout){selectedLayout.value={...x}}
async function savePosition(){if(!selectedLayout.value)return;const x=selectedLayout.value;await mutate(()=>apiRequest(`/api/admin/shelves/${x.shelfId}/layout`,{method:'PUT',body:JSON.stringify(x)}),'位置已保存，2D/3D 已刷新')}
async function saveSize(){if(!selectedLayout.value)return;const x=selectedLayout.value;await mutate(()=>apiRequest(`/api/admin/shelves/${x.shelfId}`,{method:'PUT',body:JSON.stringify(x)}),'尺寸已保存，2D/3D 已刷新')}
async function toggleShelf(s:Shelf){await mutate(()=>apiRequest(`/api/admin/shelves/${s.id}/enabled`,{method:'PUT',body:JSON.stringify({enabled:s.status!=='ACTIVE'})}),s.status==='ACTIVE'?'货架已停用':'货架已启用')}
async function toggleSlot(id:number,enabled:boolean){await mutate(()=>apiRequest(`/api/admin/slots/${id}/enabled`,{method:'PUT',body:JSON.stringify({enabled})}),'仓位状态已更新')}
onMounted(load)
</script>
<template><section class="page"><header class="page-heading"><div><p class="eyebrow">ADMIN CONTROL · DIGITAL LAYOUT</p><h1>仓库布局管理</h1><p>预览不写库；Java 事务成功后刷新同一 WarehouseSnapshot</p></div><button class="ghost" @click="load">刷新</button></header><p v-if="error" class="error" role="alert">{{error}}</p><p v-if="notice" class="success">{{notice}}</p><div v-if="loading" class="state-panel">正在加载…</div><div v-else class="settings-grid">
<article class="action-card"><h2>系统信息</h2><div class="mini-metrics"><b>{{info.users}}<small>员工</small></b><b>{{info.shelves}}<small>货架</small></b><b>{{info.slots}}<small>仓位</small></b></div><p class="muted">2D 与 3D 共用服务器真相。</p></article>
<article class="action-card"><h2>新增员工</h2><form @submit.prevent="addUser"><input v-model="userForm.username" required placeholder="账号"><input v-model="userForm.displayName" required placeholder="姓名"><input v-model="userForm.password" required minlength="6" type="password" placeholder="密码"><select v-model="userForm.role"><option>STAFF</option><option>ADMIN</option></select><button class="primary compact" :disabled="busy">新增</button></form></article>
<article class="action-card wide"><h2>AI Warehouse Agent</h2><p class="muted">只生成白名单计划；预览不写库，必须由管理员再次确认后才由 Java 事务执行。</p><form @submit.prevent="generateAgentPlan"><input v-model="agentCommand" required aria-label="AI 仓库指令"><button class="primary compact" :disabled="busy">生成 AI 计划</button></form><div v-if="agentPlan" class="layout-preview"><header><b>{{agentPlan.action.summary}}</b><span>{{agentPlan.action.intent}} · {{agentPlan.preview.shelfCount}} 架 / {{agentPlan.preview.slotCount}} 仓位 · {{agentPlan.status}}</span></header><div class="ghost-shelves"><div v-for="item in agentPlan.preview.shelves" :key="item.shelf.shelfCode"><b>{{item.shelf.shelfCode}}</b><span>{{item.layout.levels}}×{{item.layout.columns}}</span><small>X {{item.layout.positionX.toFixed(1)}} · Z {{item.layout.positionZ.toFixed(1)}}</small></div></div><div class="button-row"><button type="button" class="primary compact" :disabled="busy" @click="confirmAgentPlan">确认执行</button><button type="button" class="ghost" :disabled="busy" @click="agentPlan=null">修改指令</button><button type="button" class="ghost" :disabled="busy" @click="cancelAgentPlan">取消计划</button></div></div></article>
<article class="action-card wide"><h2>新增 / 批量新增货架</h2><form class="shelf-create-form" @submit.prevent="generatePreview"><label>区域<input v-model="shelfForm.zone" required></label><label>数量<input v-model.number="shelfForm.count" type="number" min="1" max="50"></label><label>层<input v-model.number="shelfForm.levels" type="number" min="1" max="20"></label><label>列<input v-model.number="shelfForm.columns" type="number" min="1" max="30"></label><label>宽<input v-model.number="shelfForm.width" type="number" step=".1"></label><label>高<input v-model.number="shelfForm.height" type="number" step=".1"></label><label>深<input v-model.number="shelfForm.depth" type="number" step=".1"></label><label>布局<select v-model="shelfForm.layoutMode"><option>GRID</option><option>WIDE_MAIN_AISLE</option><option>TWO_SIDED_AISLE</option></select></label><label>每排<input v-model.number="shelfForm.maxShelvesPerRow" type="number"></label><label>架间距<input v-model.number="shelfForm.shelfGap" type="number" step=".1"></label><label>通道<input v-model.number="shelfForm.aisleGap" type="number" step=".1"></label><button class="primary compact" :disabled="busy">生成预览</button></form><div v-if="preview" class="layout-preview"><header><b>{{preview.shelfCount}} 架 / {{preview.slotCount}} 仓位</b><span>确认前数据库零写入</span></header><div class="ghost-shelves"><div v-for="item in preview.shelves" :key="item.shelf.shelfCode"><b>{{item.shelf.shelfCode}}</b><span>{{item.layout.levels}}×{{item.layout.columns}}</span><small>X {{item.layout.positionX.toFixed(1)}} · Z {{item.layout.positionZ.toFixed(1)}}</small></div></div><div class="button-row"><button class="primary compact" :disabled="busy" @click="confirmCreate">确认创建</button><button class="ghost" @click="preview=null">取消</button></div></div></article>
<article class="action-card wide"><h2>移动 / 扩缩容 / 停用</h2><div class="layout-list"><button v-for="x in snapshot?.layouts" :key="x.shelfId" class="parcel-card" @click="editLayout(x)"><b>{{snapshot?.shelves.find(s=>s.id===x.shelfId)?.shelfCode}}</b><small>{{x.columns}}列×{{x.levels}}层 · ({{x.positionX}}, {{x.positionZ}})</small></button></div><form v-if="selectedLayout" class="layout-form" @submit.prevent><label v-for="key in ['positionX','positionY','positionZ','rotationY','width','height','depth','columns','levels']" :key="key">{{key}}<input v-model.number="(selectedLayout as any)[key]" type="number" step=".1"></label><button type="button" class="primary compact" :disabled="busy" @click="savePosition">保存位置</button><button type="button" class="primary compact" :disabled="busy" @click="saveSize">保存尺寸/层列</button><button v-if="selectedShelf" type="button" class="danger" @click="toggleShelf(selectedShelf)">{{selectedShelf.status==='ACTIVE'?'停用':'启用'}}</button></form></article>
<article class="action-card wide"><h2>仓位状态</h2><div class="slot-admin"><label v-for="slot in snapshot?.slots" :key="slot.id"><span>{{slot.slotCode}}</span><input type="checkbox" :checked="slot.enabled" @change="toggleSlot(slot.id,($event.target as HTMLInputElement).checked)"></label></div></article>
<article class="action-card wide"><h2>员工</h2><table><tbody><tr v-for="u in users" :key="u.id"><td>{{u.username}}</td><td>{{u.displayName}}</td><td>{{u.role}}</td><td><button class="ghost" @click="toggleUser(u)">{{u.enabled?'禁用':'启用'}}</button></td></tr></tbody></table></article></div></section></template>
