<script setup lang="ts">
import{computed,onMounted,reactive,ref}from'vue';import{apiRequest}from'@/api/client';import{useWarehouseStore}from'@/stores/warehouse';import type{ShelfLayout,User,WarehouseSnapshot}from'@/types/api'
const warehouse=useWarehouseStore(),users=ref<User[]>([]),snapshot=ref<WarehouseSnapshot|null>(null),loading=ref(false),error=ref(''),notice=ref(''),form=reactive({username:'',password:'',displayName:'',role:'STAFF'}),selectedLayout=ref<ShelfLayout|null>(null)
const systemInfo=computed(()=>({users:users.value.length,shelves:snapshot.value?.shelves.length??0,slots:snapshot.value?.slots.length??0,enabled:snapshot.value?.slots.filter(s=>s.enabled).length??0}))
async function load(){loading.value=true;error.value='';try{[users.value,snapshot.value]=await Promise.all([apiRequest<User[]>('/api/admin/users'),apiRequest<WarehouseSnapshot>('/api/admin/warehouse')]);await warehouse.refresh()}catch(e){error.value=e instanceof Error?e.message:'管理数据加载失败'}finally{loading.value=false}}
async function addUser(){try{await apiRequest('/api/admin/users',{method:'POST',body:JSON.stringify(form)});notice.value='员工已新增';Object.assign(form,{username:'',password:'',displayName:'',role:'STAFF'});await load()}catch(e){error.value=e instanceof Error?e.message:'新增失败'}}
async function toggleUser(u:User){try{await apiRequest(`/api/admin/users/${u.id}/enabled`,{method:'PUT',body:JSON.stringify({enabled:!u.enabled})});await load()}catch(e){error.value=e instanceof Error?e.message:'更新失败'}}
function editLayout(x:ShelfLayout){selectedLayout.value={...x}}
async function saveLayout(){if(!selectedLayout.value)return;try{await apiRequest(`/api/admin/layouts/${selectedLayout.value.shelfId}`,{method:'PUT',body:JSON.stringify(selectedLayout.value)});notice.value='布局已保存，2D/3D 已刷新';await load()}catch(e){error.value=e instanceof Error?e.message:'布局保存失败'}}
async function toggleSlot(id:number,enabled:boolean){try{await apiRequest(`/api/admin/slots/${id}/enabled`,{method:'PUT',body:JSON.stringify({enabled})});await load()}catch(e){error.value=e instanceof Error?e.message:'仓位状态更新失败'}}
onMounted(load)
</script>
<template><section class="page"><header class="page-heading"><div><p class="eyebrow">ADMIN CONTROL</p><h1>系统管理</h1><p>仅 ADMIN；服务端同步执行权限与业务校验</p></div><button class="ghost" @click="load">刷新</button></header><p v-if="error" class="error" role="alert">{{error}}</p><p v-if="notice" class="success">{{notice}}</p><div v-if="loading" class="state-panel">正在加载系统配置…</div><div v-else class="settings-grid">
<article class="action-card"><h2>系统信息</h2><div class="mini-metrics"><b>{{systemInfo.users}}<small>员工</small></b><b>{{systemInfo.shelves}}<small>货架</small></b><b>{{systemInfo.enabled}}/{{systemInfo.slots}}<small>启用仓位</small></b></div><p class="muted">Java 17 HttpServer · JDBC · MySQL · Vue 3 · Three.js</p><p class="muted">备份/恢复涉及服务器本地文件路径，当前保留在 legacy Swing 管理端，不提供不安全的伪 Web 按钮。</p></article>
<article class="action-card"><h2>用户管理</h2><form class="inline-form" @submit.prevent="addUser"><input v-model="form.username" required placeholder="账号"><input v-model="form.displayName" required placeholder="姓名"><input v-model="form.password" required minlength="6" type="password" placeholder="初始密码"><select v-model="form.role"><option>STAFF</option><option>ADMIN</option></select><button class="primary compact">新增</button></form><table><thead><tr><th>账号</th><th>姓名</th><th>角色</th><th>状态</th><th></th></tr></thead><tbody><tr v-for="u in users" :key="u.id"><td>{{u.username}}</td><td>{{u.displayName}}</td><td>{{u.role}}</td><td>{{u.enabled?'启用':'禁用'}}</td><td><button class="ghost" @click="toggleUser(u)">{{u.enabled?'禁用':'启用'}}</button></td></tr></tbody></table></article>
<article class="action-card wide"><h2>仓库布局</h2><div class="layout-list"><button v-for="x in snapshot?.layouts" :key="x.shelfId" class="parcel-card" @click="editLayout(x)">货架 #{{x.shelfId}}<small>{{x.columns}} 列 × {{x.levels}} 层 · ({{x.positionX}}, {{x.positionZ}})</small></button></div><form v-if="selectedLayout" class="layout-form" @submit.prevent="saveLayout"><label v-for="key in ['positionX','positionY','positionZ','rotationY','width','height','depth','columns','levels']" :key="key">{{key}}<input v-model.number="(selectedLayout as any)[key]" type="number" step="0.1" required></label><button class="primary">保存布局</button></form></article>
<article class="action-card wide"><h2>货架 / 仓位状态</h2><div class="slot-admin"><label v-for="slot in snapshot?.slots" :key="slot.id"><span>{{slot.slotCode}}</span><input type="checkbox" :checked="slot.enabled" @change="toggleSlot(slot.id,($event.target as HTMLInputElement).checked)"></label></div></article></div></section></template>
